metrics:
  - default: cosine.yaml

collectors:
  - default: SimSiamCollector.yaml

selectors:
  - default: DenseTripletSelector.yaml

losses:
  - default: PosPairLoss.yaml

models:
  - trunk: resnet50_scratch.yaml
  - embedder: simsiam_projector.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: RMSprop_trunk.yaml
  - embedder: RMSprop_embedder.yaml

schedulers:
  - trunk: on_plateau.yaml
  - embedder: on_plateau.yaml

gradclipper:
  - trunk: gradclipper.yaml
  - embedder: gradclipper.yaml

transforms:
  - train: moco_train_transforms.yaml
  - test: moco_eval_transforms.yaml

datasets:
  - train: imagenet_train.yaml
  - test: imagenet_test.yaml

# samplers:
#   - train: MPerClassSampler.yaml

collatefns:
  - train: simsiam.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml


